application: database-1208
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /bower_components
  static_dir: client/bower_components
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
